update info_mix set img='/azbooking/view/admin/Themes/kcfinder/upload/images/danhmuc_tour/848166.jpg',name='Chính sách và quy định chung',content='<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	<strong style=\"margin: 0px; padding: 0px;\">1. Who we are?</strong></p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	Located in Hanoi, the capital city of Vietnam, Mix Tourist is a local tour operator based in Vietnam, specialized in tailor made inbound package tours for individuals, small groups and large ones to Vietnam. With many years of experience in tourism along with constant efforts of officers and staff to make excellent services with the most preferential price, we&rsquo;re the reliable for partners and customers.</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	<img alt=\"\" height=\"351\" src=\"http://mixtourist.com/uploads/images/August/logomixtourist.jpg\" style=\"margin: 0px auto; padding: 0px; border: none; display: block;\" width=\"600\" /></p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	The Mix Tourist team provides professional and attentive service for holiday, corporate, special interest and cruise travel. Members of the team have lived and travelled intensively throughout Vietnam and it would be hard to find a region that at least one of the team hasn&rsquo;t travelled to! We recognize the importance of careful planning and we have the skills and knowledge to help you get the best out of your travel experience. Our genuine love of all things travel means that whether it be travel by plane, cruise ship, self-drive, we can ensure your plans run smoothly and you have the most amazing journey &ndash; and we love when you come back and share your precious memories with us. As a result, we have a lot of repeat visitors and they are willing to recommend us. That&rsquo;s the way we have been developing company so far.</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	Come along and explore one of the most beautiful magnificient sights in the world!</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	We are very happy to welcome you to our beautiful country!</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	<strong style=\"margin: 0px; padding: 0px;\">2. What we do?</strong><br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	- Provide full useful travel information &amp; high quality travel services&nbsp; in Vietnam, Laos and Cambodia<br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	- Provide the tailor-made holidays and private tours with different styles<br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	- Make the hotel bookings throughout Indochina at affordable price<br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	- Offer quality private transportation throughout Indochina<br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	- Arrange Visa services<br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	- Provide MICE services<br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	- Make the air ticket &amp; train ticket booking<br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	-&nbsp; Provide professional Interpreter, Translator and Tour guide<br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	<strong style=\"margin: 0px; padding: 0px;\">3. Why travel with us?</strong></p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	From the beginning, we have maintained the strong values which have brought our company from strength to strength. Not losing sights of our commitment to service and customer satisfaction, we have cultivated a brand name with excellence, quality and value. Our tour offers you the very best that the region has to offer in term of accommodation, transportation, food, tour guide, sightseeing and enriched cultural experiences.</p>
<p>
	<span style=\"color: rgb(60, 59, 59); font-family: Arial;\">- Interesting Tailor- made Trip for all budgets</span></p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	The well customized and interesting itinerary is our key point. As we live in Indochina, we know our place deeply. We believe that your tour should be full of cherished memories to take home. Embark on your dream holiday with the peace of mind that you are traveling with the experts who have knowledge and expertise to design and provide holidays to suit your interest</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	- Reasonable price</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	Our tours offer great value for money.We set up and maintain the solid relationships with major airlines, hotels and local service suppliers throughout Vietnam, Cambodia &amp; Laos. This enables us to offer a great variety of well designed and personalized tours at competitive&nbsp; price while keeping the high-quality services. We have no extra hidden costs.&nbsp; All inclusions and exclusions are mentioned at our final confirmation for your trip.<br style=\"margin: 0px; padding: 0px;\" />
	<br style=\"margin: 0px; padding: 0px;\" />
	- Our promise of SAFTY</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	We constantly monitor the region in case any problems should arise and all our guides have first aid training. We also require that all Asia View Travel&rsquo;s clients have adequate medical and travel insurance before participating in our tour programs. We take care and assist our customers before, during and after their holidays.</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	- Professional, knowledgable and friendly&nbsp; Team and Tour guides</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	With Mix Tourist you are always able to speak to a sales representative day or night. Drop us an email or call us 24 hours a day to speak to our dedicated team working to help you around the clock . Our team are happy to listen to your requirement and give you personal, friendly and expert suggestion based on your interest, schedule, budget, level of energy and travel preferences. Our staff are the local people who have deep knowledge about the region and willing to introduce it&rsquo;s beauty to you. Their expertise and years of travel experience makes them the reliable travel consultants and best tour operators.</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	- Reliable and authorized Tour Operator in Vietnam</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	We have been operating under the control of Vietnam National Administration of Tourism and have International Tour Operator Licence issued by Vietnam National Administration of Tourism. We are proud to say that we are the reliable and authorized Tour Operator in Vietnam.</p>
<p style=\"margin: 0px; padding: 6px 0px; line-height: 20px; color: rgb(60, 59, 59); font-family: Arial;\">
	<strong style=\"margin: 0px; padding: 0px;\">4. Our tour Categories</strong></p>
<ul style=\"margin: 0px; padding-right: 0px; padding-left: 0px; list-style: none; color: rgb(60, 59, 59); font-family: Arial;\">
	<li style=\"margin: 0px; padding: 0px; list-style: none;\">
		From Luxury to Standard&nbsp; Classic Tours &amp; Family holiday: Cultural, Historical, Natural discovery</li>
	<li style=\"margin: 0px; padding: 0px; list-style: none;\">
		Special interest tours: Honeymoon, Culinary Tour, Beach holiday, Golf Tour, Educational Tour</li>
	<li style=\"margin: 0px; padding: 0px; list-style: none;\">
		Halong bay cruises &amp; Mekong river cruises</li>
	<li style=\"margin: 0px; padding: 0px; list-style: none;\">
		Adventure&nbsp; Tours: Trekking, cycling, diving , Kayaking &amp; exploration more</li>
	<li style=\"margin: 0px; padding: 0px; list-style: none;\">
		Multi-Country Tours: Vietnam , Laos &amp; Cambodia</li>
	<li style=\"margin: 0px; padding: 0px; list-style: none;\">
		Free &amp; Easy packages</li>
</ul>
',title='Chính sách và quy định chung',keyword='Chính sách và quy định chung',description='Chính sách và quy định chung' where id=1;
update info_mix set img='/azbooking/view/admin/Themes/kcfinder/upload/images/danhmuc_tour/848166.jpg',name='Chính sách và quy định chung',content='<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">1. ĐIỀU KHOẢN CHUNG</strong></p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	AZbooking.vn l&agrave; trang b&aacute;n dịch vụ du lịch ( tour du lịch, ph&ograve;ng kh&aacute;ch sạn, v&eacute; m&aacute;y bay&hellip;) của c&ocirc;ng ty du lịch&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Mix Tourist</strong>. Gi&aacute; tất cả c&aacute;c dịch vụ được t&iacute;nh theo tiền đồng (Việt Nam &ndash; VNĐ).&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Gi&aacute; dịch vụ</strong>&nbsp;được thể hiện trong phần gi&aacute;, v&agrave; c&oacute; liệt k&ecirc; chi tiết c&aacute;c dịch vụ được thể hiện trong phần:&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Bao gồm, kh&ocirc;ng bao gồm, lưu &yacute;.</strong>&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Mix Tourist</strong>&nbsp;chỉ thanh to&aacute;n c&aacute;c dịch trong phần&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Bao gồm</strong>.</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	&nbsp;</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	&nbsp;</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">2. ĐĂNG K&Yacute; DỊCH VỤ )</strong></p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	Qu&yacute; kh&aacute;ch c&oacute; thể đăng k&yacute; dịch vụ bằng c&aacute;ch chọn sản phẩm dịch vụ du lịch cần mua, xem chi tiết về sản phẩm, gi&aacute;, dịch vụ bao gồm v&agrave; kh&ocirc;ng bao gồm, những th&ocirc;ng tin lưu &yacute; kh&aacute;c. Tiếp theo k&iacute;ch v&agrave;o n&uacute;t đặt ( Đặt tour/ đặt ph&ograve;ng/ đặt v&eacute; ), v&agrave; điều c&aacute;c th&ocirc;ng tin theo mẫu đặt tour m&agrave;&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Mix Tourist</strong>&nbsp;cung cấp ( Lưu &yacute; điều đầy đủ th&ocirc;ng tin ở mục ở đ&aacute;nh dấu sao ). Sau đ&oacute; click v&agrave;o n&uacute;t đồng &yacute; v&agrave; gửi y&ecirc;u cầu. Nh&acirc;n vi&ecirc;n của&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Mix Tourist</strong>&nbsp;sau khi nhận được th&ocirc;ng tin sẽ li&ecirc;n lạc với Qu&yacute; kh&aacute;ch để hướng dẫn thủ tục th&agrave;nh to&aacute;n v&agrave; c&aacute;c thủ tục kh&aacute;ch chưa ho&agrave;n th&agrave;nh, V&agrave; cuối c&ugrave;ng l&agrave; x&aacute;c nhận đơn h&agrave;ng cho Qu&yacute; kh&aacute;ch.</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Lưu &yacute;:</strong>&nbsp;Qu&yacute; kh&aacute;ch c&oacute; thể đăng k&yacute; dịch vụ khi l&agrave; th&agrave;nh vi&ecirc;n v&agrave; cả khi chưa phải l&agrave; th&agrave;nh vi&ecirc;n của trang&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">AZbooking.</strong></p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	&nbsp;</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">3. ĐẶT CỌC, THANH TO&Aacute;N, GIAO NHẬN</strong></p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">* Đặt cọc v&agrave; thanh To&aacute;n:</strong>&nbsp;Sau khi đăng k&yacute;, qu&yacute; kh&aacute;ch vui l&ograve;ng cung cấp đầy đủ th&ocirc;ng tin, đặt cọc, thanh to&aacute;n cho&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Mix Tourist.</strong>( Số tiền đặt cọc v&agrave; thanh to&aacute;n ph&ugrave; thuộc v&agrave; từng dịch vụ )</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	- Thanh to&aacute;n bằng tiền mặt tại c&ocirc;ng ty.</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	- Chuyển khoản qua ng&acirc;n h&agrave;ng theo th&ocirc;ng tin sau:</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	T&ecirc;n t&agrave;i khoản: C&Ocirc;NG TY CP DỊCH VỤ DU LỊCH MIX ( MIX TOURIST )</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	Ng&acirc;n h&agrave;ng: Vietcombank &ndash; chi nh&aacute;nh Ba Đ&igrave;nh &ndash; H&agrave; Nội</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	T&agrave;i khoản: VNĐ: 0611001895909</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	Lưu &yacute;: Khi qu&yacute; kh&aacute;ch d&ugrave;ng dịch thanh to&aacute;n trực tuyến, ngo&agrave;i chi ph&iacute; dịch vụ, Qu&yacute; kh&aacute;ch c&ograve;n phả trả th&ecirc;m c&aacute;c khoản ph&iacute; của nh&agrave; cung cấp dịch vụ thanh to&aacute;n trực tuyến sau:</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	+ C&agrave; thẻ ATM nội địa: 0.2%</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	+ C&agrave; thẻ ATM nước ngo&agrave;i: 3.85%</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	+ Thẻ VISA/MASTER: 1.5% tr&ecirc;n tổng gi&aacute; trị thanh to&aacute;n</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	+ Thanh to&aacute;n qua cổng thanh to&aacute;n trực tuyến Paypal: Kh&aacute;ch h&agrave;ng đặt tour v&agrave; thanh to&aacute;n trực tiếp tr&ecirc;n cổng thanh to&aacute;n quốc tế Paypal, ph&iacute;: 3.9% + 0.3 USD</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	Việc thanh to&aacute;n xem l&agrave; ho&agrave;n tất khi Mix Tourist nhận được đủ tiền v&agrave;o đ&uacute;ng ng&agrave;y qui định. Bất kỳ việc thanh to&aacute;n chậm trễ dẫn đến việc hủy dịch vụ kh&ocirc;ng thuộc tr&aacute;ch nhiệm của Mix Tourist.</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	Với h&igrave;nh thức thanh to&aacute;n chuyển khoản: Khi thực hiện việc chuyển khoản, qu&yacute; kh&aacute;ch vui l&ograve;ng ghi r&otilde; họ t&ecirc;n, địa chỉ, điện thoại v&agrave; nội dung chuyến du lịch cụ thể đ&atilde; được qu&yacute; kh&aacute;ch chọn đăng k&yacute;.</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	Sau khi thực hiện việc chuyển khoản, qu&yacute; kh&aacute;ch vui l&ograve;ng Fax hoặc gửi bản scan Ủy Nhiệm Chi về c&ocirc;ng ty v&agrave; liện hệ nh&acirc;n vi&ecirc;n của Mix Tourist để nhận được x&aacute;c nhận bằng văn bản của Mix Tourist về việc đặt dịch vụ v&agrave; thanh to&aacute;n th&agrave;nh c&ocirc;ng.</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	*&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Giao nhận:</strong>&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Mix Tourist</strong>&nbsp;sẽ hỗ trợ giao nhận v&agrave; thu tiền tại nh&agrave; của của Qu&yacute; kh&aacute;ch với c&aacute;c h&oacute;a đơn tr&ecirc;n 1 triệu VND ( chỉ &aacute;p dụng cho khu vực nội th&agrave;nh H&agrave; Nội v&agrave; TP.HCM )</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	&nbsp;</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">4. HỦY DỊCH VỤ V&Agrave; ĐIỀU KIỆN HO&Agrave;N HỦY</strong></p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	- Trường hợp bị bủy bỏ do&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Mix Tourist</strong>:</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	Nếu du lịch&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Mix Tourist&nbsp;</strong>kh&ocirc;ng thực hiện được dịch vụ du lịch,&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">Mix Tourist</strong>&nbsp;phải b&aacute;o ngay cho kh&aacute;ch h&agrave;ng biết v&agrave; thanh to&aacute;n lại cho kh&aacute;ch h&agrave;ng to&agrave;n bộ số tiền m&agrave; kh&aacute;ch h&agrave;ng đ&atilde; đ&oacute;ng trong v&ograve;ng 3 ng&agrave;y kể từ l&uacute;c việc th&ocirc;ng b&aacute;o hủy dịch vụ du lịch bằng tiền mặt hoặc chuyển khoản.</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	-&nbsp;&nbsp;&nbsp; Trường hợp bị hủy v&eacute; do&nbsp;<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">kh&aacute;ch h&agrave;ng</strong>:</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	T&ugrave;y v&agrave;o từng dịch vụ du lịch c&oacute; qui định ho&agrave;n hủy ri&ecirc;ng ( Qu&yacute; kh&aacute;ch xem chi tiết phần sản phẩm v&agrave; c&aacute;c điều khoản về gi&aacute; bao gồm, kh&ocirc;ng bao gồm v&agrave; phần lưu &yacute; ) Việc phạt ho&agrave;n, hủy c&oacute; thể l&ecirc;n tới 100% tổng gi&aacute; th&agrave;nh dịch vụ đ&atilde; đăng k&yacute;. Việc huỷ dịch vụ du lịch phải được th&ocirc;ng b&aacute;o trực tiếp với C&ocirc;ng ty hoặc qua fax, email v&agrave; phải được C&ocirc;ng ty x&aacute;c nhận. Việc huỷ bỏ bằng điện thoại sẽ kh&ocirc;ng được chấp nhận.</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	<strong style=\"border: 0px; outline: 0px; vertical-align: baseline; background: transparent; margin: 0px; padding: 0px;\">- Lưu &yacute;:&nbsp;</strong>Trường hợp hủy dịch vụ do sự cố kh&aacute;ch quan như: thi&ecirc;n tai, khủng bổ, dịch bệnh,&hellip; Mix Tourist sẽ kh&ocirc;ng chịu tr&aacute;ch nhiệm bồi thường th&ecirc;m bất kỳ chi ph&iacute; n&agrave;o ngo&agrave;i việc ho&agrave;n trả tiền tour,</p>
<p style=\"border: 0px; outline: 0px; vertical-align: baseline; background-image: initial; background-position: initial; background-size: initial; background-repeat: initial; background-attachment: initial; background-origin: initial; background-clip: initial; margin: 0px; padding: 0px; color: rgb(0, 0, 0); font-family: Tohoma, Helvetica, sans-serif;\">
	- Trường hợp bất khả kh&aacute;ng: Nếu chương tr&igrave;nh du lịch bị hủy bỏ hoặc thay đổi bởi một trong hai b&ecirc;n v&igrave; một l&yacute; do bất khả kh&aacute;ng (chiến tranh, thi&ecirc;n tai, khủng bố&hellip;), th&igrave; hai b&ecirc;n sẽ kh&ocirc;ng chịu bất kỳ nghĩa vụ bồi ho&agrave;n c&aacute;c tổn thất đ&atilde; xảy ra v&agrave; kh&ocirc;ng chịu bất tr&aacute;ch nhiệm nhiệm ph&aacute;p l&yacute; n&agrave;o. Tuy nhi&ecirc;n mỗi b&ecirc;n c&oacute; tr&aacute;ch nhiệm cố gắng tối đa để gi&uacute;p đỡ b&ecirc;n bị thiệt hại nhằm giảm thiểu c&aacute;c tổn thất g&acirc;y ra v&igrave; l&yacute; do bất khả kh&aacute;ng.</p>
',title='Chính sách và quy định chung',keyword='Chính sách và quy định chung',description='Chính sách và quy định chung' where id=1;
update info_mix set img='/azbooking/view/admin/Themes/kcfinder/upload/images/danhmuc_tour/848166.jpg',name='Chính sách bảo mật thông tin',content='<pre>
</pre>
<pre>
Ch&iacute;nh s&aacute;ch bảo mật th&ocirc;ng tin</pre>
',title='Chính sách bảo mật thông tin',keyword='Chính sách bảo mật thông tin',description='Chính sách bảo mật thông tin' where id=2;
update info_mix set img='/azbooking/view/admin/Themes/kcfinder/upload/images/danhmuc_tour/848166.jpg',name='Hình thức thanh toán',content='<pre>
H&igrave;nh thức thanh to&aacute;n</pre>
',title='Hình thức thanh toán',keyword='Hình thức thanh toán',description='Hình thức thanh toán' where id=3;
update info_mix set img='/azbooking/view/admin/Themes/kcfinder/upload/images/danhmuc_tour/848166.jpg',name='Quy định đổi trả - hoàn tiền',content='<pre>
Quy định đổi trả - ho&agrave;n tiền</pre>
',title='Quy định đổi trả - hoàn tiền',keyword='Quy định đổi trả - hoàn tiền',description='Quy định đổi trả - hoàn tiền' where id=4;
update info_mix set img='/azbooking/view/admin/Themes/kcfinder/upload/images/danhmuc_tour/848166.jpg',name='Chính sách quy trình xử lý khiếu nại',content='<pre>
Ch&iacute;nh s&aacute;ch quy tr&igrave;nh xử l&yacute; khiếu nại</pre>
',title='Chính sách quy trình xử lý khiếu nại',keyword='Chính sách quy trình xử lý khiếu nại',description='Chính sách quy trình xử lý khiếu nại' where id=5;
update info_mix set img='/azbooking/view/admin/Themes/kcfinder/upload/images/danhmuc_tour/848166.jpg',name='Chính sách vận chuyển và giao nhận',content='<pre>
Ch&iacute;nh s&aacute;ch vận chuyển v&agrave; giao nhận</pre>
',title='Chính sách vận chuyển và giao nhận',keyword='Chính sách vận chuyển và giao nhận',description='Chính sách vận chuyển và giao nhận' where id=6;
