insert into khachsan_img (danhmuc_id,name,img,position) values ('1','Somerset Central TD Hai Phong','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/1.jpg','1');
insert into khachsan_img (danhmuc_id,name,img,position) values ('1','Somerset Central TD Hai Phong','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/2.jpg','2');
insert into khachsan_img (danhmuc_id,name,img,position) values ('1','Somerset Central TD Hai Phong','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg','');
update khachsan_img set danhmuc_id='1',name='Somerset Central TD Hai Phong',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg',position='4' where id=3;
update khachsan_img set danhmuc_id='1',name='Somerset Central TD Hai Phong',img='/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/3.jpg',position='3' where id=3;
insert into khachsan_img (danhmuc_id,name,img,position) values ('1','Somerset Central TD Hai Phong','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/4.jpg','4');
insert into khachsan_img (danhmuc_id,name,img,position) values ('1','Somerset Central TD Hai Phong','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/5.jpg','5');
insert into khachsan_img (danhmuc_id,name,img,position) values ('1','Somerset Central TD Hai Phong','/azbooking/view/admin/Themes/kcfinder/upload/images/khachsan/6.jpg','6');
insert into khachsan_img (danhmuc_id,name,img,position) values ('6','asdfasdf','','');
delete from khachsan_img where danhmuc_id=;
delete from khachsan_img where danhmuc_id=6;
