update news set view='1' where id=1;
update news set view='2' where id=1;
update news set view='3' where id=1;
update news set view='4' where id=1;
update news set view='5' where id=1;
update news set view='6' where id=1;
update news set view='7' where id=1;
update news set view='1' where id=5;
update news set view='2' where id=5;
